/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
        "secondary-fixed-dim": "#b7c8e1",
        "surface-container-highest": "#e0e3e5",
        "primary-fixed-dim": "#b1c5ff",
        "on-primary-fixed": "#001946",
        "on-surface-variant": "#434653",
        "surface-variant": "#e0e3e5",
        "background": "#f7f9fb",
        "secondary-container": "#d0e1fb",
        "surface-container-lowest": "#ffffff",
        "surface-container-high": "#e6e8ea",
        "on-tertiary-fixed-variant": "#005049",
        "surface-container-low": "#f2f4f6",
        "surface": "#f7f9fb",
        "on-tertiary-container": "#13d4c4",
        "tertiary-fixed": "#57fae9",
        "tertiary": "#003e38",
        "primary-fixed": "#dae2ff",
        "on-secondary": "#ffffff",
        "secondary-fixed": "#d3e4fe",
        "on-secondary-container": "#54647a",
        "surface-dim": "#d8dadc",
        "outline": "#737784",
        "outline-variant": "#c3c6d5",
        "tertiary-container": "#005750",
        "on-error": "#ffffff",
        "secondary": "#505f76",
        "on-primary-fixed-variant": "#00419e",
        "on-secondary-fixed-variant": "#38485d",
        "surface-container": "#eceef0",
        "on-error-container": "#93000a",
        "inverse-primary": "#b1c5ff",
        "on-tertiary-fixed": "#00201d",
        "inverse-on-surface": "#eff1f3",
        "inverse-surface": "#2d3133",
        "on-primary-container": "#a5bdff",
        "tertiary-fixed-dim": "#2addcd",
        "error": "#ba1a1a",
        "primary": "#00327d",
        "on-surface": "#191c1e",
        "on-background": "#191c1e",
        "on-tertiary": "#ffffff",
        "on-primary": "#ffffff",
        "surface-bright": "#f7f9fb",
        "primary-container": "#0047ab",
        "surface-tint": "#2559bd",
        "on-secondary-fixed": "#0b1c30",
        "error-container": "#ffdad6"
      },
      "borderRadius": {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      "fontFamily": {
        "headline": ["Manrope"],
        "body": ["Inter"],
        "label": ["Inter"]
      }
    },
  },
  plugins: [],
}